#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'git'
cookbook "mercurial"
cookbook "mysql"

# external

cookbook 'unicorn',
  :git => 'https://github.com/opscode-cookbooks/unicorn'

cookbook 'mercurial-env',
  :git => 'https://github.com/shimizukawa/chef-mercurial-env'

cookbook "rvm",
  :git => 'https://github.com/fnichol/chef-rvm'

cookbook "rvm-redmine",
  :git => 'https://github.com/shimizukawa/chef-rvm-redmine'

cookbook "bp-redmine",
  :git => 'https://github.com/shimizukawa/chef-bp-redmine'
